#!/usr/bin/python3

import rospy
from gpt_server.srv import GPTGenerate, GPTGenerateRequest, GPTGenerateResponse
from openai import OpenAI
import json
import pandas as pd
import sys
import os 
import random
from std_msgs.msg import String

from nltk.sentiment.vader import SentimentIntensityAnalyzer

from pal_interaction_msgs.msg import TtsAction, TtsGoal
from actionlib import SimpleActionClient

from percy_paths import percy_data_dir

class GPT:
    """
    ChatGPT server class.
    This will run in the background, waiting for a request to be made.
    GPT server accepts a string as request and outputs a string generated by ChatGPT.
    """

    def __init__(self):
        self.sentimentAnalyser = SentimentIntensityAnalyzer()

        rospy.init_node('gpt_server')
        id = rospy.get_param('~id','test')
        self.service = rospy.Service('gpt_generate', GPTGenerate, self.OnRequest)
        data_root = percy_data_dir(__file__)
        session_dir = os.path.join(data_root, str(id))
        os.makedirs(session_dir, exist_ok=True)
        # intialize the chat history
        self.history_file_path = os.path.join(session_dir, 'chat_history.json')
        self.messages = []
        rospy.loginfo('GPT node started')

        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            rospy.logfatal("OPENAI_API_KEY environment variable is not set.")
            sys.exit(1)
        self.client = OpenAI(api_key=api_key)
        # self.messages = ""
        self.user_profile=""
        self.history = ""
        # Extract the profile from the JSON file
        json_file_path = os.path.join(session_dir, 'profile.json')
        # self.emotion = "neutral"
        # set the timer for the topic changing'You are empathic, passionate, professional but super friendly and interested to learn more about the users and their personal information,I will give you the user profile information that contains several pairs of questions and answers, I want you to remember this profile of {self.profile} and have a converstaion with the user based on the information of each pari of question and answerEvery time you make a response, use the user response with his\\her emotions of {self.realtime_emotion} to generate the next responseif it possible try to avoid yes/no questionswhen you communicate with users, use a friendly tone and simple vocabrary, do not use a high level and academic wordsone question per time and always response in English'}, {'role': 'assistant', 'content': 'What are your favorite movies or TV show genres? (Multiple Choices)'}, {'role': 'user', 'content': 'Sci-fi'}, {'role': 'assistant', 'content': "That's awesome! Sci-fi movies and TV shows are so intriguing. What is it about sci-fi that you enjoy the most?"}]

        self.topic_changer = self.TopicChanger(json_file_path)
        self.to_change_topic = True # set the flag to change the topic
        self.first_question = True
        self.utterance_counter = 0 # set the utterance counter to change topic
        # once the below function is executed, then we set the flag to call TopicChanger to change the topic
        # self.Totimer = rospy.Timer(rospy.Duration(120), self.set_topic_flag) # this is the timer to change the topic every 2 minutes
        self.profile =""
        with open(json_file_path, "r") as json_file:
            self.profile = json.load(json_file)

        self.screen_pub = rospy.Publisher('dialogue_robot',String, queue_size=10)
        self.emotiondetection_realtime = rospy.Subscriber('emotiondetect_result', String, self.emotion_result_callback)
        self.realtime_emotion = "neutral"

        print('Connecting to /tts.')
        self.ttsPub = SimpleActionClient('/tts', TtsAction)
        self.ttsPub.wait_for_server()
        print('Connected to /tts!')


    #  the emotion detection result callback function -> realtime emotion
    def emotion_result_callback(self, data):
        self.realtime_emotion = data.data
        # print(f'Emotion detected: {self.realtime_emotion}')
        return self.realtime_emotion

    def set_topic_flag(self):
        if self.utterance_counter >= 3:
            self.to_change_topic = True
            self.utterance_counter = 0  

    def OnRequest(self, data: GPTGenerateRequest):
        text_from_speech = data.request  # Speech recognized by the user
        # self.emotion = data.initialEmotion

        # finalEmotion = data.finalEmotion
        input_text = {"role": "user", "content": text_from_speech}
        sentiment = self.sentimentAnalyser.polarity_scores(text_from_speech)['compound']
        sentimentstr = ''

        if sentiment < -0.05:
            sentimentstr = 'negative'
        elif sentiment > 0.05:
            sentimentstr = 'positive'
        else:
            sentimentstr = 'neutral'

        text_to_append = {"role": "user", "content": text_from_speech, "emotion": self.realtime_emotion, "sentiment": sentimentstr, "sentiment_score": sentiment}
        # Append the user's input to the conversation history -> the dialogue
        self.append_to_json(text_to_append, self.history_file_path)
        print(f'Receive emotions: {self.realtime_emotion}')
        self.messages.append(input_text) # append user speech into the message

        rospy.loginfo(f"Received a request with a prompt:\n{text_from_speech}")

        # here we detect whether to change the topic or not
        # if self.to_change_topic == True or text_from_speech[:9].lower()== "new topic":
        #     # change topic and close the flag, ready for next topic
        #     question, answer = self.topic_changer.new_topic()

        #     # Play a motion to indicate the change of topic
        msg = TtsGoal()
        msg.rawtext.lang_id = 'en_gb'
        msg.rawtext.text = "<mark name='doTrick trickName=show_right_cpy'/> Let's change the topic"
        # self.ttsPub.send_goal(msg)
        self.tts.send_goal(msg)

        #     self.to_change_topic = False
        
        #     self.messages= [{"role": "system", "content":
        #     "You are empathic, passionate, professional but super friendly and interested to learn more about the users and their personal information," +
        #     "I will give you the user profile information that contains several pairs of questions and answers, I want you to remember this profile of {self.profile} and have a converstaion with the user based on the information of each pari of question and answer"+
        #     "Every time you make a response, use the user response with his\her emotions of {self.realtime_emotion} to generate the next response"+
        #     "if it possible try to avoid yes/no questions"+
        #     "when you communicate with users, use a friendly tone and simple vocabrary, do not use a high level and academic words" +
        #     "one question per time and always response in English"} ]

        #     self.messages.append(question)
        #     self.messages.append(answer)
        if self.first_question == True:
            question, answer = self.topic_changer.new_topic()
            self.first_question = False

            # Play a motion to indicate the change of topic
            # msg = TtsGoal()
            # msg.rawtext.lang_id = 'en_gb'
            # msg.rawtext.text = "<mark name='doTrick trickName=show_right_cpy'/> Nice to meet you, let's have a chat padding"
            # self.ttsPub.send_goal(msg)
            # rospy.sleep(0.5)

            self.to_change_topic = False
        
            self.messages= [{"role": "system", "content":
            "You are empathic, passionate, professional but super friendly and interested to learn more about the users and their personal information," +
            "I will give you the user profile information that contains several pairs of questions and answers, I want you to remember this profile of {self.profile} and have a converstaion with the user based on the information of each pari of question and answer"+
            "Every time you make a response, use the user response with his\her emotions of {self.realtime_emotion} to generate the next response"+
            "if it possible try to avoid yes/no questions"+
            "when you communicate with users, use a friendly tone and simple vocabrary, do not use a high level and academic words" +
            "one question per time and always response in English"} ]

            self.messages.append(question)
            self.messages.append(answer)



        if self.utterance_counter > 3:
            # change topic and close the flag, ready for next topic
            question, answer = self.topic_changer.new_topic()
            self.utterance_counter = 0

            # Play a motion to indicate the change of topic
            # msg = TtsGoal()
            # msg.rawtext.lang_id = 'en_gb'
            # # msg.rawtext.text = "<mark name='doTrick trickName=show_right_cpy'/> Let's change the topic padding  "
            # msg.rawtext.text = " Let's change the topic padding  "
            # self.ttsPub.send_goal(msg)
            


            self.to_change_topic = False
        
            self.messages= [{"role": "system", "content":
            "You are empathic, passionate, professional but super friendly and interested to learn more about the users and their personal information," +
            "I will give you the user profile information that contains several pairs of questions and answers, I want you to remember this profile of {self.profile} and have a converstaion with the user based on the information of each pari of question and answer"+
            "Every time you make a response, use the user response with his\her emotions of {self.realtime_emotion} to generate the next response"+
            "if it possible try to avoid yes/no questions"+
            "when you communicate with users, use a friendly tone and simple vocabrary, do not use a high level and academic words" +
            "one question per time and always response in English"} ]

            self.messages.append(question)
            self.messages.append(answer)


        # Get a response from ChatGPT-3.5 Turbo
        response = self.get_openai_response(self.messages)

        # Append the response to the conversation
        self.messages.append({"role": "assistant", "content": response})

        print(f'Received a request with a prompt:\n{input_text}')
        response_to_append = {"role": "assistant", "content": response}
        # append to the chat history
        self.append_to_json(response_to_append, self.history_file_path)
        print(self.messages)
        display_response = f'Role: Robot, Content: {response}'
        self.screen_pub.publish(display_response)
        self.utterance_counter+=1
        
        return response
   
    def get_openai_response(self, messages):
        chat = self.client.chat.completions.create(model="gpt-3.5-turbo", messages=messages)
        reply = chat.choices[0].message.content 
        return reply
        # return GPTGenerateResponse(response=reply)

    def append_to_json(self, data, file_path):
        # Check if the JSON file exists
        if os.path.exists(file_path):
            # If file exists, read existing JSON data
            with open(file_path, 'r') as json_file:
                existing_data = json.load(json_file)
        else:
            # If file doesn't exist, initialize with an empty list
            existing_data = []

        # Append new data to the existing data
        existing_data.append(data)

        # Write the updated data back to the JSON file
        with open(file_path, 'w') as json_file:
            json.dump(existing_data, json_file, indent=4)
    
    # def print_flag(self):
    #     rate = rospy.Rate(1)  # Rate of 1 Hz (1 message per second)
    #     while not rospy.is_shutdown():
    #         rate.sleep()  # Sleep to maintain the desired rate


    class TopicChanger:
        def __init__(self,json_path):
            # Create a set to store all the printed pairs 
            self.printed_pairs = set()
            # Specify the path to the JSON file
            self.json_path = json_path
            self.current_index = 0
            # Load the JSON data from the file
            with open(self.json_path) as f:
                self.json_data = json.load(f)

        def new_topic(self):
            if self.current_index < len(self.json_data):
                pair = self.json_data[self.current_index]
                question = pair[0]['content']
                answer = pair[1]['content']
                if (question, answer) not in self.printed_pairs:
                    print('Changing topic!')
                    print("Question:", question) 
                    print("Answer:", answer)
                    print()
                    self.printed_pairs.add((question, answer))
                    self.current_index += 1
                    rospy.logwarn(f"Current Topic Index: {self.current_index}, There are {len(self.json_data)-self.current_index} topics left. Changed to new topic {question}")
                    return {"role": "assistant", "content": question}, {"role": "user", "content": answer}
            else:
                rospy.logwarn("All Topics Discussed")
                rospy.signal_shutdown("All Topics Discussed")
 
     
          

if __name__ == '__main__':
    gpt = GPT()
    # gpt.print_flag()
    rospy.spin()# set the utterance counter to change topic
        # once the below function is executed, then we set the flag to call TopicChanger to change the topic
        # self.Totimer = rospy.Timer(rospy.Duration(120), self.set_topic_flag) # this is the timer to change the topic every 2 minutes